### ISSUE TITLE
Apply RESTful Resource Naming Convention for Ruuter endpoints

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#106]
AS A Service Manager
I WANT TO create REST endpoints for services following RESTful naming conventions
SO THAT they would follow a widely used convention and therefore be easily understandable for both Service Managers, developers, and service consumers

> See https://restfulapi.net/resource-naming for more information

### Acceptance Criteria

The following (possibly affected) Ruuter's current functionalities must remain intact

- [ ] Processing DSLs according to Request Method Type (https://github.com/buerokratt/Ruuter/issues/36)
- [ ] Making GET requests (https://github.com/buerokratt/Ruuter/issues/7)
- [ ] Making POST requests (https://github.com/buerokratt/Ruuter/issues/8)

**New functionality**

Ruuter endpoints must follow the structure of DSL folders

- [ ] https://github.com/buerokratt/Ruuter/blob/main/DSL/GET/common/skip.yml would be processed in case of GET request to http://localhost:8080/common/skip
- [ ] https://github.com/buerokratt/Ruuter/blob/main/DSL/GET/steps/assign/assign.yml would be processed in case of GET request to http://localhost:8080/steps/assign/assign
- [ ] https://github.com/buerokratt/Ruuter/blob/main/DSL/POST/scripting/passing-post-parameters.yml would be processed in case of POST request to http://localhost:8080/scripting/passing-post-parameters
- [ ] https://github.com/buerokratt/Ruuter/blob/main/DSL/POST/steps/post/post-with-used-response.yml would be processed in case of POST request to http://localhost:8080/steps/post/post-with-used-response
- [ ] None of the DSLs are processed in case there is no exact path to DSL as a `YAML` file matching with the URI

**Comment by Kristjanmn** [comment]
Works with local testing. Adjusted existing yaml files and examples to match new naming convention.
This also removes white label error pages.
