### ISSUE TITLE
Switch logging requests and responses both on every DSL and their steps level

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Ruuter#47]
AS A Service Manager
I WANT TO have control over storing client requests and responses in Ruuter logs
SO THAT I could use it for debugging and/or building custom services based on it

#### Default settings

Define as a base configuration parameter the default value to

- [ ] log `request` content in Ruuter logs
- [ ] log `response` content in Ruuter logs
- [ ] allow overwriting the above base configuration settings within Ruuter DSL steps

#### Custom settings for every DSL step

- [ ] Log `request` content of a specific DSL step in Ruuter logs
- [ ] Log `response` content of a specific DSL step in Ruuter logs
- [ ] Do not log the `request` content of a specific DSL step in Ruuter logs if defined otherwise in base settings
- [ ] Do not log the `response` content of a specific DSL step in Ruuter logs if defined otherwise in base settings

**Comment by turnerrainer** [comment]
Development done by initially planned 29.06.2023, but merged 03.08.2023 due to @turnerrainer being afk for a while.
